sudo: false
language: cpp
compiler:
  - gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7
install:
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 --slave /usr/bin/g++ g++ /usr/bin/g++-7
script:
  - make test bftest mhtest hmhtest serial_test mctest
  - ./test
  - ./bftest
  - ./mhtest
  - ./mctest
  - ./hmhtest
  - ./serial_test
notifications:
    slack: jhu-genomics:BbHYSks7DhOolq80IYf6m9oe
    rooms:
      - jhu-genomics:BbHYSks7DhOolq80IYf6m9oe#meta_trees
